<?php require_once('templates/partials/header.phtml'); ?>
	<main>		
		<h2> Ajout d'un plat </h2>
		<div class="plat">
			<form class="colonne" action="libraries/application.php?task=ajout" method="POST">			
					<input required type="text" name="image" placeholder="saisir l'adresse de l'image">
					<input required type="text" name="titre" placeholder="saisir le titre du plat">
					<input required type="text" name="description" placeholder="saisir la description du plat">
			        <input required  type="number" step="0.01" name="prix" placeholder="saisir le prix">
			        <select name="type">
							  <option value="entree">entree</option> 
							  <option value="plat" >plat</option>
							  <option value="dessert">dessert</option>	
					</select>		  	
				    <button type="submit">Enregistrer!</button>		    
			</form>
		</div>			 
<?php require_once('templates/partials/footer.phtml');?>
