<?php require_once('templates/partials/header.phtml');?>
<main>	
		<h2> modifier un plat </h2>
		<div class="plat">
		<form  class="colonne" action="libraries/application.php?task=modifier&id=<?=$monplat['id']?>" method="POST">

				<input type="text" name="image" value="<?=$monplat['image'] ?>">
				<input required type="text" name="titre"  value="<?=$monplat['titre']?>">
				<input required type="text" name="description" value="<?=$monplat['description']?>">
		        <input required  type="number" step="0.01" name="prix" value="<?=$monplat['prix']?>">
			        <SELECT name="type" size="1">
			        <?php if($monplat['type']=="entree") :?> <option selected value="entree" ><?php else : ?> <option value="entree" ><?php endif; ?> entrée </option>

			        <?php if($monplat['type']=="plat") :?><option selected value="plat" ><?php else : ?> <option value="plat"> <?php endif; ?>  plat </option>
			    
 					<?php if($monplat['type']=="dessert") :?><option selected value="dessert" ><?php else : ?> <option value="dessert"> <?php endif; ?> dessert </option>	 
								  	          	
	                </SELECT>  
		      <!--   <input required  type="txt" name="type" value="<?=$monplat['type']?>">	-->

			    <button type="submit">Enregistrer!</button>
		</form>
		</div >			 
	<?php require_once('templates/partials/footer.phtml');?>