
<?php
require_once('templates/partials/header.phtml');
?>
	<main>
		<h2> RESERVATION </h2>

		<!--<form action="libraries/application.php?task=panier" method="POST" >  ---->
		<form id="f-reservation" action="libraries/application.php?task=ajout" method="POST">
				<h3>Penser à remplir tous les champs </h3>
				<input type="text" name ="nom" placeholder="saisir votre nom">
				<input type="text" name ="prenom" placeholder="saisir votre prenom">
				<input type="text" name ="email" placeholder="saisir votre email">
		        <input type="date" name ="date" placeholder="saisir votre date">
		        <h4><span>Penser pour le weekend a indiquer le midi ou le soir dans votre message</span> </h4>
		        <textarea type="message" name ="message" placeholder="saisir votre message"rows="10" cols="50"></textarea>
		        <h3>saisir le nombre de convives</h3>
			        <select name="nbpersonnes"> 
							  <option value="1" >1 personne </option> 
							  <option value="2" >2 personnes</option>
							  <option value="3" >3 personnes</option>
							  <option value="4" >4 personnes</option>
							  <option value="5" >5 personnes</option>
							  <option value="6"  >6 personnes</option>
							  <option value="7"  >7personnes</option>
							  <option value="8"  >8 personnes</option>
							  <option value="9"  >9 personnes</option>
							  <option value="10" >10 personnes</option>
					</select>
				<button type="submit">Enregistrer!</button>
		</form>
 <?php
require_once('templates/partials/footer.phtml');
?>